# ------------------------------------------------------
# Page tree
# ------------------------------------------------------
nav:

  - 🎓 Astra Tutorials:
    - 🏠 Home: index.md
    - Astra Core:
      - Create Token: astra-create-token.md
    - AstraDB:
      - Create Database: astra-create-instance.md
      - Download SecureConnectBundle: astra-download-scb.md
      - Resume a database: astra-resume-db.md
      - Multi Regions: astra-multi-regions.md
      - CQL Proxy: astra-cqlproxy.md
      - FAQ: astra-faq.md
    - Astra Steaming:
      - Create Astra Streaming Topic: astra-create-topic.md
   
  - 📥 Data Management:
    - 🏠 Home: section-work-with-data.md
    - Load Data:
      - Astra Data Loader: data-astradataloader.md
      - DSBulk: data-dsbulk.md
      - NoSQL Bench: data-nosqlbench.md
    - Explore You Data:
      - Cqlsh: todo.md
      - Netflix Data Explorer 🚧: todo.md
      - Datagrip: todo.md
      - DBSchema: todo.md
      - DBeaver: todo.md
      - MindDB: todo.md
      - TablePlus: todo.md
    - Data Modelling:
      - Kashliev KDM: http://kdm.kashliev.com/
      
  - 🛠️ Develop:
    - 🏠 List: section-coding.md
    - Stargate Apis:
      - REST: todo.md
      - Document: api-document.md
      - graphQL: todo.md
      - gRPC: todo.md
    - Languages:
      - Java: language-java.md
      - Javascript: language-javascript.md
      - Python: language-python.md
      - GoLang: language-go.md
      - CSharp: language-csharp.md
      - Scala: language-scala.md
      - Rust: language-rust.md
    - Frameworks:
      - Spring: framework-spring.md
      - Quarkus: framework-quarkus.md
      - Micronaut: framework-micronaut.md
  
  - 📦 Tools:
    - 📦 Tools List: section-tools.md
    - Developers IDE:
      - IntelliJ : todo.md
      - Eclipse : todo.md
      - VSCode : todo.md
      - Gitpod : todo.md
    - Notebooks:
      - Jupyter Notebooks : todo.md
      - DataStax Studio : todo.md
      - Apache Zeppelin : todo.md
    - Integration Middlewares:
      - Apache Airflow : tool-apache-airflow.md
      - Apache Nifi : todo.md
      - Apache Spark : todo.md
      - Pentaho Data Integration : todo.md
      - Temporal : todo.md
      
# ------------------------------------------------------
# Settings
# ------------------------------------------------------

# Project information
site_name: Awesome Astra
site_url: https://awesome-astra.github.io
site_author: Cedrick Lunven
site_description: >-
 Your Wiki to implement Awesome Applications with Astra

# Repository
repo_name: awesome-astra/docs
repo_url: https://github.com/awesome-astra/docs
edit_uri: ""

# Theme
theme:
 name: material
 language: en
 features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
 palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

 #favicon: assets/favicon.png
 #icon:
 #   logo: docs/img/logo-go.png
 
 include_search_page: false
 search_index_only: true

# Mardown Support
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  #- pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search

# Customization
extra:
  analytics:
    provider: google
    property: G-ZMZXZME49E
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCAIQY251avaMv7bBv5PCo-A
    - icon: fontawesome/brands/github
      link: https://github.com/clun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/clunven
    - icon: fontawesome/brands/discord
      link: https://dtsx.io/discord

    
            