name: NPM Publish
on:
  workflow_run:
    workflows: [Build and deploy mkdocs to github pages]
    types: [completed]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "package"
          message: "Package Publish"
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
      - run: git config --global user.name 'dieterrandolph'
      - run: git config --global user.email 'dieter.randolph@datastax.com'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.AA_NPM }}
          registry: https://npm.pkg.github.com
